spring:
  datasource:
    url: jdbc:mysql://cursobd.c38ow00koesq.us-east-2.rds.amazonaws.com:3306/editorialweb
    username: root
    password: '12345678'
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none