spring:
  datasource:
    url: jdbc:postgresql://urlamazon:5432/editorialweb
    username: sa
    password: 'password'
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none