spring:
  datasource:
    url: jdbc:mysql://[urlamazon]:3306/editorialweb
    username: root
    password: 'password'
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none